model_path: /home/michal/code/inference_engine/models/mnist_ffn_complex.onnx
model_format: onnx
execution_provider: CPU
batch_size: 1
inputs:
  - name: input1
    shape: [1, 1, 28, 28]
    data_type: FLOAT32
outputs:
  - name: output1
    shape: [1, 10]
    data_type: FLOAT32